[package]
name = "qecdec"
version = "0.1.0"
edition = "2021"

[lib]
name = "qecdec"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25", features = ["extension-module"] }
numpy = "0.25"
ndarray = "0.15"